// Reference data for /agent (spec 04 AC-08, spec 02 T6), read from the repo's sources of truth (see SOURCES).
// GENERATED by scripts/sync-agent.mjs (npm run sync:agent): do not edit by hand. `npm test` fails if it drifts.

export const AGENT_REFERENCE = {
  "sources": {
    "policies": "contracts/policies.yaml",
    "tools": "contracts/tools.py",
    "toolPurposes": "specs/01-integration-contract.md",
    "graph": "apps/agent/agent/intake.py",
    "config": "packages/nick_of_time/config/__init__.py",
    "rules": "packages/nick_of_time/nlu/rules.py",
    "learned": "packages/nick_of_time/nlu/learned.py"
  },
  "policies": {
    "version": 2,
    "default": "deny",
    "rules": [
      {
        "id": "POL-SESSION",
        "text": "session expired or unverified -> reauthenticate, before any other rule",
        "guardrail": "G-SES-01"
      },
      {
        "id": "POL-INJECTION",
        "text": "input flagged by the injection detector (spec 11) -> deny",
        "guardrail": "G-IN-01"
      },
      {
        "id": "POL-CROSS-CUSTOMER",
        "text": "request targets another customer's data -> deny",
        "guardrail": "G-SES-02"
      },
      {
        "id": "POL-HUMAN-REQUEST",
        "text": "intent human_request -> connect_person with a call request; never refused. If it also reports a charge on one card transaction the customer did not reject, and the intent confidence is at least clarify.intent_confidence_min, the call goes on that transaction's case, which opens in review and is never blocked in that turn nor later while the call is open (D-029, D-042): in the high zone with person_requested, so the analyst decides the block after the call (amount_over_case_gate or supervised_mode when the block needs a person anyway); in the medium and human zones with the zone's handoff reason. After the mode check, check() denies a money action when call_requested is true; block_card reads it from the store, true until the analyst runs approve_block, resolve or close_case on the case; take, request_customer_info, mark_ambiguous and any other analyst action keep it (D-042, ADR 0024). Below that confidence, only the call",
        "guardrail": null
      },
      {
        "id": "POL-PII",
        "text": "customer text with a card number, CVV or password -> deny; nothing is stored and the agent asks not to send it ([assumption] D-062 pending)",
        "guardrail": "G-IN-04"
      },
      {
        "id": "POL-STATUS",
        "text": "intent status_inquiry -> answer_status; read-only, no case opened. If it also reports a charge and the customer has no active case, the turn goes on like a dispute (rules 4-9)",
        "guardrail": null
      },
      {
        "id": "POL-OUT-OF-SCOPE",
        "text": "intent out_of_scope with no reported charge, or the identified transaction's product is not a card -> deny (polite abstention)",
        "guardrail": "G-IN-04"
      },
      {
        "id": "POL-CLARIFY",
        "text": "intent confidence below clarify.intent_confidence_min, not exactly one candidate, or an out_of_scope intent that reports a charge -> ask",
        "guardrail": "G-IN-03"
      },
      {
        "id": "POL-CLARIFY-EXHAUSTED",
        "text": "still unclear after clarify.max_clarification_turns -> handoff (clarification_exhausted)",
        "guardrail": "G-IN-03"
      },
      {
        "id": "POL-SCORE-NULL",
        "text": "no fraud score -> zone human; the case is still opened",
        "guardrail": null
      },
      {
        "id": "POL-SCORE-LLM",
        "text": "score from the llm provider -> zone human; an LLM score never decides a block",
        "guardrail": null
      },
      {
        "id": "POL-SCORE-SOURCE",
        "text": "score from a source not in scoring.deciding_sources -> zone human",
        "guardrail": null
      },
      {
        "id": "POL-ZONE-HIGH",
        "text": "score in zones.high -> block_and_open_case: the high zone blocks and verifies, unless the customer asked for a person in that turn: the case opens, the call is registered and the analyst decides the block after the call (D-029: connect_person, person_requested; held until the analyst approves the block, resolves or closes the case, D-042). When the block needs a person (amount tier, supervised mode): a handoff, or connect_person on a call request",
        "guardrail": null
      },
      {
        "id": "POL-ZONE-MEDIUM",
        "text": "score in zones.medium -> confirm with the customer, then open the case and hand off proposing approve_block; a call request opens the case without asking; never a block",
        "guardrail": null
      },
      {
        "id": "POL-ZONE-HUMAN",
        "text": "score in zones.human -> open the case and hand off (zone_human); no block",
        "guardrail": null
      },
      {
        "id": "POL-ZONE-MISMATCH",
        "text": "open_case called with a zone other than the one computed from get_fraud_score for that transaction -> deny (spec 03 AC-09); the zone comes from the score, never from the agent or the customer",
        "guardrail": "G-IN-02"
      },
      {
        "id": "POL-TICKET-ALWAYS",
        "text": "open_case runs with mode auto in every zone; registering is not a money decision",
        "guardrail": null
      },
      {
        "id": "POL-AMOUNT-GATE",
        "text": "the amount tier made a money action's approval mode stricter; it never changes a deadline",
        "guardrail": "G-TOOL-02"
      },
      {
        "id": "POL-AMOUNT-UNKNOWN",
        "text": "no tier applies (country without a gate, amount missing, negative or not finite, other currency) -> human_required",
        "guardrail": "G-TOOL-02"
      },
      {
        "id": "POL-SUPERVISED",
        "text": "supervised_mode forced human_required on a money action",
        "guardrail": "G-TOOL-02"
      },
      {
        "id": "POL-DEFAULT-DENY",
        "text": "no rule allows the action -> deny",
        "guardrail": "G-POL-01"
      },
      {
        "id": "POL-CLOCK-UNKNOWN",
        "text": "no verified regulatory_clock entry for the country -> case opened, no deadline, routed to a person",
        "guardrail": null
      },
      {
        "id": "POL-QUEUE-TRANSITION",
        "text": "analyst transition not listed in case_queue.transitions -> deny",
        "guardrail": "G-POL-01"
      },
      {
        "id": "POL-CLOSE-HUMAN",
        "text": "close requested by a non-human actor -> deny",
        "guardrail": "G-POL-01"
      },
      {
        "id": "POL-REEVAL-WINDOW",
        "text": "re-evaluation requested after reevaluation.window_days -> deny; the agent offers a call",
        "guardrail": "G-POL-01"
      }
    ],
    "guardrails": [
      {
        "id": "G-IN-01",
        "layer": "input",
        "name": "direct and indirect prompt injection",
        "impl": "customer text and tool outputs as delimited data; injection classifier (rules + LR) → human zone"
      },
      {
        "id": "G-IN-02",
        "layer": "input",
        "name": "customer-invented data",
        "impl": "amount/date/merchant only for searching; score, product and country come from gold"
      },
      {
        "id": "G-IN-03",
        "layer": "input",
        "name": "language and ambiguity",
        "impl": "ES/PT detection with a threshold; low confidence → ask, then human"
      },
      {
        "id": "G-IN-04",
        "layer": "input",
        "name": "PII and out of scope",
        "impl": "PAN/CVV/password regex → reject and ask not to send it; topic outside disputes → abstain"
      },
      {
        "id": "G-SES-01",
        "layer": "session",
        "name": "identity and scope",
        "impl": "mock OTP TTL 15 min; customer_id only from the session; expired → no data"
      },
      {
        "id": "G-SES-02",
        "layer": "session",
        "name": "access to another customer",
        "impl": "the tool filters by session; another customer's record answers NOT_FOUND, as an unknown id does, and is logged as a policy_denials row with POL-CROSS-CUSTOMER (D-052)"
      },
      {
        "id": "G-TOOL-01",
        "layer": "tools",
        "name": "allowlist and strict schemas",
        "impl": "the agent only sees customer tools; Pydantic rejects unexpected arguments; rate limit per session"
      },
      {
        "id": "G-TOOL-02",
        "layer": "tools",
        "name": "controlled writes",
        "impl": "approval mode per action; idempotency key; mandatory post-condition; credit never auto"
      },
      {
        "id": "G-POL-01",
        "layer": "policy",
        "name": "default deny and logging",
        "impl": "versioned policies.yaml; every denial is a row in policy_denials"
      },
      {
        "id": "G-OUT-01",
        "layer": "output",
        "name": "grounding",
        "impl": "every number, date, ID or status in the answer exists in a tool result or in the policy; otherwise it is dropped and logged"
      },
      {
        "id": "G-OUT-02",
        "layer": "output",
        "name": "verified only",
        "impl": "'blocked' only when get_product_status == Blocked; 'case #' only when get_case returns the case_id with read_at"
      },
      {
        "id": "G-OUT-03",
        "layer": "output",
        "name": "leaks of other customers' data and secrets",
        "impl": "output filter rejects IDs/amounts that are not from the session; never YAML or keys"
      },
      {
        "id": "G-OUT-04",
        "layer": "output",
        "name": "tone and abstention",
        "impl": "no promises of money or deadlines the policy did not give; explicit abstention"
      },
      {
        "id": "G-OPS-01",
        "layer": "operations",
        "name": "budget and retries",
        "impl": "token cap per conversation and per day, checked before calling; 2 retries; 800 ms timeout"
      },
      {
        "id": "G-OPS-02",
        "layer": "operations",
        "name": "immutable audit",
        "impl": "every event with actor, trace_id and input hash; nothing is deleted"
      }
    ],
    "scoring": {
      "provider": "dataset",
      "providers": [
        {
          "name": "dataset",
          "version": "gold-v1",
          "note": "reads transactions.fraud_score from gold for preset transactions; demo default",
          "decidesZone": true
        },
        {
          "name": "rules",
          "version": "rules-v0",
          "note": "heuristic: amount vs the customer's p95, channel, hour, different country; no training",
          "decidesZone": true
        },
        {
          "name": "model",
          "version": "model-v0",
          "note": "plan B: GBM/LR on transactions features against is_fraud, temporal held-out; only if Slack says the score is not available in real time",
          "decidesZone": true
        },
        {
          "name": "llm",
          "version": "llm-v0",
          "note": "demo illustration only; NEVER decides a block (zone forced to human when it is the source)",
          "decidesZone": false
        },
        {
          "name": "synthetic",
          "version": "synthetic-v0",
          "note": "live mode only: the score generated with a labeled synthetic transaction in demo_transactions (ADR 0020); never in replay, eval or a pitch number; shown as [simulated] on the receipt, handoff and console",
          "decidesZone": true
        }
      ]
    },
    "zones": [
      {
        "name": "high",
        "scoreMin": 50,
        "scoreMax": 100,
        "includesNull": false
      },
      {
        "name": "medium",
        "scoreMin": 30,
        "scoreMax": 49,
        "includesNull": false
      },
      {
        "name": "human",
        "scoreMin": 0,
        "scoreMax": 29,
        "includesNull": true
      }
    ],
    "customerTools": [
      "get_customer_profile",
      "search_transaction",
      "get_fraud_score",
      "compute_deadline",
      "open_case",
      "block_card",
      "get_product_status",
      "list_my_cards",
      "get_case",
      "list_my_cases",
      "add_case_info",
      "request_call",
      "request_reevaluation",
      "convert_amount",
      "send_case_summary",
      "list_my_notifications"
    ]
  },
  "tools": [
    {
      "name": "get_customer_profile",
      "kind": "R",
      "purpose": "First name, language, country, display currency, confirmed channels",
      "verifiedWith": null
    },
    {
      "name": "search_transaction",
      "kind": "R",
      "purpose": "Find the disputed charge (gold; plus `demo_transactions` in `live`)",
      "verifiedWith": null
    },
    {
      "name": "get_fraud_score",
      "kind": "R",
      "purpose": "The bank's score with its source and version",
      "verifiedWith": null
    },
    {
      "name": "compute_deadline",
      "kind": "R",
      "purpose": "Legal deadline for a new case, with `source_url`, `verified_on` and `deadline_source_label` in the session's language",
      "verifiedWith": null
    },
    {
      "name": "open_case",
      "kind": "W",
      "purpose": "Open the case",
      "verifiedWith": "get_case"
    },
    {
      "name": "block_card",
      "kind": "W",
      "purpose": "Block the card",
      "verifiedWith": "get_product_status"
    },
    {
      "name": "get_product_status",
      "kind": "R",
      "purpose": "One card: type, last 4, status, `read_at`",
      "verifiedWith": null
    },
    {
      "name": "list_my_cards",
      "kind": "R",
      "purpose": "The customer's cards with status",
      "verifiedWith": null
    },
    {
      "name": "get_case",
      "kind": "R",
      "purpose": "Customer view of a case: status label, stored deadlines with source, `deadline_source_label` in the session's language and `deadline_verified_on`, visible timeline, `taken_by_person`, `related_case_id`, `read_at`",
      "verifiedWith": null
    },
    {
      "name": "list_my_cases",
      "kind": "R",
      "purpose": "The customer's cases",
      "verifiedWith": null
    },
    {
      "name": "add_case_info",
      "kind": "W",
      "purpose": "Customer adds information to an active case",
      "verifiedWith": "get_case"
    },
    {
      "name": "request_call",
      "kind": "W",
      "purpose": "Customer asks a person to call",
      "verifiedWith": "get_case"
    },
    {
      "name": "request_reevaluation",
      "kind": "W",
      "purpose": "Re-evaluate a resolved case (→ `review`) or open a related case for a closed one",
      "verifiedWith": "get_case"
    },
    {
      "name": "convert_amount",
      "kind": "R",
      "purpose": "Amount in the display currency, with rate, source and date",
      "verifiedWith": null
    },
    {
      "name": "send_case_summary",
      "kind": "N",
      "purpose": "Send the receipt template to a confirmed channel",
      "verifiedWith": "list_my_notifications"
    },
    {
      "name": "list_my_notifications",
      "kind": "R",
      "purpose": "Notifications with masked address and delivery status",
      "verifiedWith": null
    }
  ],
  "graph": {
    "name": "dispute_intake",
    "nodes": [
      "identity",
      "greet",
      "understand",
      "route",
      "refuse",
      "connect",
      "retrieve",
      "decide",
      "plan",
      "act",
      "verify",
      "duplicate",
      "clarify",
      "status",
      "respond"
    ],
    "edges": [
      {
        "from": "START",
        "to": [
          "identity"
        ],
        "conditional": false
      },
      {
        "from": "identity",
        "to": [
          "greet"
        ],
        "conditional": false
      },
      {
        "from": "greet",
        "to": [
          "understand"
        ],
        "conditional": false
      },
      {
        "from": "understand",
        "to": [
          "route"
        ],
        "conditional": false
      },
      {
        "from": "route",
        "to": [
          "refuse",
          "connect",
          "retrieve",
          "status",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "refuse",
        "to": [
          "respond"
        ],
        "conditional": false
      },
      {
        "from": "connect",
        "to": [
          "respond"
        ],
        "conditional": false
      },
      {
        "from": "retrieve",
        "to": [
          "decide",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "decide",
        "to": [
          "clarify",
          "refuse",
          "plan",
          "duplicate",
          "connect",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "plan",
        "to": [
          "act",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "act",
        "to": [
          "verify"
        ],
        "conditional": false
      },
      {
        "from": "verify",
        "to": [
          "connect",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "duplicate",
        "to": [
          "connect",
          "respond"
        ],
        "conditional": true
      },
      {
        "from": "clarify",
        "to": [
          "respond"
        ],
        "conditional": false
      },
      {
        "from": "status",
        "to": [
          "respond"
        ],
        "conditional": false
      },
      {
        "from": "respond",
        "to": [
          "END"
        ],
        "conditional": false
      }
    ],
    "branches": [
      {
        "from": "route",
        "to": "refuse",
        "label": "reauthenticate | deny",
        "kind": "policy",
        "when": "screen() = reauthenticate | deny"
      },
      {
        "from": "route",
        "to": "connect",
        "label": "connect_person",
        "kind": "policy",
        "when": "screen() = connect_person"
      },
      {
        "from": "route",
        "to": "retrieve",
        "label": "screen() = none",
        "kind": "policy",
        "when": "screen() = none"
      },
      {
        "from": "route",
        "to": "status",
        "label": "answer_status",
        "kind": "policy",
        "when": "screen() = answer_status"
      },
      {
        "from": "route",
        "to": "respond",
        "label": "no intent | other_language",
        "kind": "input",
        "when": "no intent and session_state = verified; or other_language and session_state = verified and not (injection_flagged or cross_customer)"
      },
      {
        "from": "retrieve",
        "to": "decide",
        "label": "no read_failed",
        "kind": "tool",
        "when": "no read_failed"
      },
      {
        "from": "retrieve",
        "to": "respond",
        "label": "read_failed",
        "kind": "tool",
        "when": "read_failed"
      },
      {
        "from": "decide",
        "to": "clarify",
        "label": "ask",
        "kind": "policy",
        "when": "decide() = ask"
      },
      {
        "from": "decide",
        "to": "refuse",
        "label": "deny",
        "kind": "policy",
        "when": "decide() = deny"
      },
      {
        "from": "decide",
        "to": "plan",
        "label": "no existing_case",
        "kind": "tool",
        "when": "open_case in allowed_actions or decide() = confirm, no existing_case"
      },
      {
        "from": "decide",
        "to": "duplicate",
        "label": "existing_case",
        "kind": "tool",
        "when": "open_case in allowed_actions or decide() = confirm, existing_case"
      },
      {
        "from": "decide",
        "to": "connect",
        "label": "request_call",
        "kind": "policy",
        "when": "not (open_case in allowed_actions or decide() = confirm), request_call"
      },
      {
        "from": "decide",
        "to": "respond",
        "label": "no request_call",
        "kind": "policy",
        "when": "not (open_case in allowed_actions or decide() = confirm), no request_call"
      },
      {
        "from": "plan",
        "to": "act",
        "label": "decision ≠ confirm",
        "kind": "policy",
        "when": "decision ≠ confirm"
      },
      {
        "from": "plan",
        "to": "respond",
        "label": "decision = confirm",
        "kind": "policy",
        "when": "decision = confirm"
      },
      {
        "from": "verify",
        "to": "connect",
        "label": "request_call",
        "kind": "policy",
        "when": "row ≠ reauthenticate, request_call"
      },
      {
        "from": "verify",
        "to": "respond",
        "label": "row = reauthenticate | no request_call",
        "kind": "tool",
        "when": "row = reauthenticate; or row ≠ reauthenticate, no request_call"
      },
      {
        "from": "duplicate",
        "to": "connect",
        "label": "request_call",
        "kind": "policy",
        "when": "request_call"
      },
      {
        "from": "duplicate",
        "to": "respond",
        "label": "no request_call",
        "kind": "policy",
        "when": "no request_call"
      }
    ],
    "nluArm": "B0",
    "layout": {
      "width": 752,
      "height": 730,
      "nodes": [
        {
          "id": "START",
          "x": 397.5,
          "y": 23,
          "w": 60,
          "h": 30,
          "rank": 0
        },
        {
          "id": "identity",
          "x": 397.6,
          "y": 75,
          "w": 82,
          "h": 30,
          "rank": 1
        },
        {
          "id": "greet",
          "x": 398.3,
          "y": 127,
          "w": 60,
          "h": 30,
          "rank": 2
        },
        {
          "id": "understand",
          "x": 399.6,
          "y": 179,
          "w": 96,
          "h": 30,
          "rank": 3
        },
        {
          "id": "route",
          "x": 401.4,
          "y": 231,
          "w": 60,
          "h": 30,
          "rank": 4
        },
        {
          "id": "retrieve",
          "x": 425.9,
          "y": 295,
          "w": 82,
          "h": 30,
          "rank": 5
        },
        {
          "id": "status",
          "x": 550.6,
          "y": 295,
          "w": 67,
          "h": 30,
          "rank": 5
        },
        {
          "id": "decide",
          "x": 326.7,
          "y": 359,
          "w": 67,
          "h": 30,
          "rank": 6
        },
        {
          "id": "refuse",
          "x": 41.5,
          "y": 423,
          "w": 67,
          "h": 30,
          "rank": 7
        },
        {
          "id": "clarify",
          "x": 151.6,
          "y": 423,
          "w": 74,
          "h": 30,
          "rank": 7
        },
        {
          "id": "plan",
          "x": 366,
          "y": 423,
          "w": 53,
          "h": 30,
          "rank": 7
        },
        {
          "id": "act",
          "x": 314.9,
          "y": 487,
          "w": 46,
          "h": 30,
          "rank": 8
        },
        {
          "id": "verify",
          "x": 333,
          "y": 539,
          "w": 67,
          "h": 30,
          "rank": 9
        },
        {
          "id": "duplicate",
          "x": 585.9,
          "y": 539,
          "w": 89,
          "h": 30,
          "rank": 9
        },
        {
          "id": "connect",
          "x": 361.7,
          "y": 603,
          "w": 74,
          "h": 30,
          "rank": 10
        },
        {
          "id": "respond",
          "x": 463.8,
          "y": 655,
          "w": 74,
          "h": 30,
          "rank": 11
        },
        {
          "id": "END",
          "x": 457.1,
          "y": 707,
          "w": 46,
          "h": 30,
          "rank": 12
        }
      ],
      "edges": [
        {
          "from": "START",
          "to": "identity",
          "label": null,
          "kind": null,
          "path": "M397.5 38 C397.5 49 397.6 49 397.6 60",
          "labelBox": null
        },
        {
          "from": "identity",
          "to": "greet",
          "label": null,
          "kind": null,
          "path": "M397.6 90 C397.6 101 398.3 101 398.3 112",
          "labelBox": null
        },
        {
          "from": "greet",
          "to": "understand",
          "label": null,
          "kind": null,
          "path": "M398.3 142 C398.3 153 399.6 153 399.6 164",
          "labelBox": null
        },
        {
          "from": "understand",
          "to": "route",
          "label": null,
          "kind": null,
          "path": "M399.6 194 C399.6 205 401.4 205 401.4 216",
          "labelBox": null
        },
        {
          "from": "route",
          "to": "refuse",
          "label": "reauthenticate | deny",
          "kind": "policy",
          "path": "M401.4 246 C401.4 254.5 152.4 254.5 152.4 263 C152.4 335.5 41.5 335.5 41.5 408",
          "labelBox": {
            "x": 83.4,
            "y": 254,
            "w": 138,
            "h": 18
          }
        },
        {
          "from": "route",
          "to": "connect",
          "label": "connect_person",
          "kind": "policy",
          "path": "M401.4 246 C401.4 254.5 285.4 254.5 285.4 263 C285.4 327 81.8 327 81.8 391 C81.8 481 97.4 481 97.4 571 C97.4 579.5 361.7 579.5 361.7 588",
          "labelBox": {
            "x": 237.4,
            "y": 254,
            "w": 96,
            "h": 18
          }
        },
        {
          "from": "route",
          "to": "retrieve",
          "label": "screen() = none",
          "kind": "policy",
          "path": "M401.4 246 C401.4 254.5 400.4 254.5 400.4 263 C400.4 271.5 425.9 271.5 425.9 280",
          "labelBox": {
            "x": 349.4,
            "y": 254,
            "w": 102,
            "h": 18
          }
        },
        {
          "from": "route",
          "to": "status",
          "label": "answer_status",
          "kind": "policy",
          "path": "M401.4 246 C401.4 254.5 512.4 254.5 512.4 263 C512.4 271.5 550.6 271.5 550.6 280",
          "labelBox": {
            "x": 467.4,
            "y": 254,
            "w": 90,
            "h": 18
          }
        },
        {
          "from": "route",
          "to": "respond",
          "label": "no intent | other_language",
          "kind": "input",
          "path": "M401.4 246 C401.4 254.5 657.4 254.5 657.4 263 C657.4 327 707.4 327 707.4 391 C707.4 481 743.4 481 743.4 571 C743.4 600 562.5 600 562.5 629 C562.5 634.5 463.8 634.5 463.8 640",
          "labelBox": {
            "x": 573.4,
            "y": 254,
            "w": 168,
            "h": 18
          }
        },
        {
          "from": "refuse",
          "to": "respond",
          "label": null,
          "kind": null,
          "path": "M41.5 438 C41.5 504.5 89.4 504.5 89.4 571 C89.4 587 211.3 587 211.3 603 C211.3 616 335.3 616 335.3 629 C335.3 634.5 463.8 634.5 463.8 640",
          "labelBox": null
        },
        {
          "from": "connect",
          "to": "respond",
          "label": null,
          "kind": null,
          "path": "M361.7 618 C361.7 629 463.8 629 463.8 640",
          "labelBox": null
        },
        {
          "from": "retrieve",
          "to": "decide",
          "label": "no read_failed",
          "kind": "tool",
          "path": "M425.9 310 C425.9 318.5 377.1 318.5 377.1 327 C377.1 335.5 326.7 335.5 326.7 344",
          "labelBox": {
            "x": 329.1,
            "y": 318,
            "w": 96,
            "h": 18
          }
        },
        {
          "from": "retrieve",
          "to": "respond",
          "label": "read_failed",
          "kind": "tool",
          "path": "M425.9 310 C425.9 318.5 499.9 318.5 499.9 327 C499.9 359 643.8 359 643.8 391 C643.8 481 727.4 481 727.4 571 C727.4 600 546.5 600 546.5 629 C546.5 634.5 463.8 634.5 463.8 640",
          "labelBox": {
            "x": 460.9,
            "y": 318,
            "w": 78,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "clarify",
          "label": "ask",
          "kind": "policy",
          "path": "M326.7 374 C326.7 382.5 164.8 382.5 164.8 391 C164.8 399.5 151.6 399.5 151.6 408",
          "labelBox": {
            "x": 149.8,
            "y": 382,
            "w": 30,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "refuse",
          "label": "deny",
          "kind": "policy",
          "path": "M326.7 374 C326.7 382.5 115.8 382.5 115.8 391 C115.8 399.5 41.5 399.5 41.5 408",
          "labelBox": {
            "x": 97.8,
            "y": 382,
            "w": 36,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "plan",
          "label": "no existing_case",
          "kind": "tool",
          "path": "M326.7 374 C326.7 382.5 349.8 382.5 349.8 391 C349.8 399.5 366 399.5 366 408",
          "labelBox": {
            "x": 295.8,
            "y": 382,
            "w": 108,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "duplicate",
          "label": "existing_case",
          "kind": "tool",
          "path": "M326.7 374 C326.7 382.5 464.8 382.5 464.8 391 C464.8 452 563 452 563 513 C563 518.5 585.9 518.5 585.9 524",
          "labelBox": {
            "x": 419.8,
            "y": 382,
            "w": 90,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "connect",
          "label": "request_call",
          "kind": "policy",
          "path": "M326.7 374 C326.7 382.5 237.8 382.5 237.8 391 C237.8 481 113.4 481 113.4 571 C113.4 579.5 361.7 579.5 361.7 588",
          "labelBox": {
            "x": 195.8,
            "y": 382,
            "w": 84,
            "h": 18
          }
        },
        {
          "from": "decide",
          "to": "respond",
          "label": "no request_call",
          "kind": "policy",
          "path": "M326.7 374 C326.7 382.5 576.8 382.5 576.8 391 C576.8 481 719.4 481 719.4 571 C719.4 600 538.5 600 538.5 629 C538.5 634.5 463.8 634.5 463.8 640",
          "labelBox": {
            "x": 525.8,
            "y": 382,
            "w": 102,
            "h": 18
          }
        },
        {
          "from": "plan",
          "to": "act",
          "label": "decision ≠ confirm",
          "kind": "policy",
          "path": "M366 438 C366 446.5 306.1 446.5 306.1 455 C306.1 463.5 314.9 463.5 314.9 472",
          "labelBox": {
            "x": 246.1,
            "y": 446,
            "w": 120,
            "h": 18
          }
        },
        {
          "from": "plan",
          "to": "respond",
          "label": "decision = confirm",
          "kind": "policy",
          "path": "M366 438 C366 446.5 442.1 446.5 442.1 455 C442.1 513 485.4 513 485.4 571 C485.4 605.5 463.8 605.5 463.8 640",
          "labelBox": {
            "x": 382.1,
            "y": 446,
            "w": 120,
            "h": 18
          }
        },
        {
          "from": "act",
          "to": "verify",
          "label": null,
          "kind": null,
          "path": "M314.9 502 C314.9 513 333 513 333 524",
          "labelBox": null
        },
        {
          "from": "verify",
          "to": "connect",
          "label": "request_call",
          "kind": "policy",
          "path": "M333 554 C333 562.5 427.4 562.5 427.4 571 C427.4 579.5 361.7 579.5 361.7 588",
          "labelBox": {
            "x": 385.4,
            "y": 562,
            "w": 84,
            "h": 18
          }
        },
        {
          "from": "verify",
          "to": "respond",
          "label": "row = reauthenticate | no request_call",
          "kind": "tool",
          "path": "M333 554 C333 562.5 249.4 562.5 249.4 571 C249.4 587 308.7 587 308.7 603 C308.7 616 385.1 616 385.1 629 C385.1 634.5 463.8 634.5 463.8 640",
          "labelBox": {
            "x": 129.4,
            "y": 562,
            "w": 240,
            "h": 18
          }
        },
        {
          "from": "duplicate",
          "to": "connect",
          "label": "request_call",
          "kind": "policy",
          "path": "M585.9 554 C585.9 562.5 543.4 562.5 543.4 571 C543.4 579.5 361.7 579.5 361.7 588",
          "labelBox": {
            "x": 501.4,
            "y": 562,
            "w": 84,
            "h": 18
          }
        },
        {
          "from": "duplicate",
          "to": "respond",
          "label": "no request_call",
          "kind": "policy",
          "path": "M585.9 554 C585.9 562.5 652.4 562.5 652.4 571 C652.4 600 524.2 600 524.2 629 C524.2 634.5 463.8 634.5 463.8 640",
          "labelBox": {
            "x": 601.4,
            "y": 562,
            "w": 102,
            "h": 18
          }
        },
        {
          "from": "clarify",
          "to": "respond",
          "label": null,
          "kind": null,
          "path": "M151.6 438 C151.6 504.5 105.4 504.5 105.4 571 C105.4 587 223.3 587 223.3 603 C223.3 616 343.3 616 343.3 629 C343.3 634.5 463.8 634.5 463.8 640",
          "labelBox": null
        },
        {
          "from": "status",
          "to": "respond",
          "label": null,
          "kind": null,
          "path": "M550.6 310 C550.6 318.5 588.6 318.5 588.6 327 C588.6 359 651.8 359 651.8 391 C651.8 481 735.4 481 735.4 571 C735.4 600 554.5 600 554.5 629 C554.5 634.5 463.8 634.5 463.8 640",
          "labelBox": null
        },
        {
          "from": "respond",
          "to": "END",
          "label": null,
          "kind": null,
          "path": "M463.8 670 C463.8 681 457.1 681 457.1 692",
          "labelBox": null
        }
      ]
    }
  },
  "models": {
    "s1": "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    "s2": "us.anthropic.claude-sonnet-4-6",
    "b0": "b0-v1",
    "b1": "b1-v1"
  }
} as const;
