// UI strings of the /agent drawings (components/agent/*), in one module and shaped like a messages dictionary so they
// can move to the i18n dictionaries (spec 16 AC-06) as they are. Placeholders are written `{name}` and filled by `fill`.

export const AGENT_UI = {
  graph: {
    title: "Graph {name}: {nodes} nodes and {edges} edges from START to END. Each node can be focused to read what it does.",
    scrollHint: "Scroll sideways to see the whole graph; the table below lists the same nodes.",
    legendLabel: "Edge colors",
    branchOn: "Branch on a {kind}",
    alwaysNext: "Always next",
    replay: "Replay",
    replayLabel: "Replay the graph drawing in order, from START to END",
    panelLabel: "Selected node",
    panelHint: "Hover a node, or Tab to one, to see what it does and what decides each way out. Esc clears.",
    goesTo: "Goes to",
    when: "when",
    always: "always",
    comesFrom: "Comes from",
    current: "Current node",
    onPath: "On this run's path",
  },
  arch: {
    title: "Services architecture: {services} services and {flows} request paths, from the browser to the data and the models.",
    legendLabel: "Path kinds",
    kinds: {
      request: "Request (HTTPS)",
      agent: "Agent run and tools",
      llm: "LLM call",
      data: "Data",
      deploy: "Delivery (CI/CD)",
    },
    play: "Walk through",
    pause: "Pause",
    previous: "Previous step",
    next: "Next step",
    step: "Step {n} of {total}",
    overview: "Overview",
    panelLabel: "Selected service or step",
    panelHint: "Walk through the request paths, or hover or Tab to a service to read its role. Esc clears.",
    sends: "Sends",
    receives: "Receives",
    stepsTitle: "Request paths, in order",
    staticView: "Static view (SVG)",
    staticNote: "· the original drawing, which also shows the notifications and the S3 bucket.",
  },
  page: {
    lead: "Every view on this page is generated from the repository's code and contracts; the tests fail when one drifts.",
    detail: "Detail →",
    viewAsTable: "View as table",
    sources: "Sources",
    lines: {
      architecture: "Agent on LangGraph Platform, customer tools as an MCP server, case state in Postgres.",
      graph: "{nodes} nodes from START to END; a branch follows the policy engine, a tool read or the understood input, never the LLM's text.",
      policies: "The bank's fraud score picks a zone, the zone picks the action, and a case opens in every zone.",
      tools: "{count} tools are the agent's only way to data; every write is read back before it counts as verified.",
      guardrails: "{count} guardrails, each in code with a case in the evaluation set.",
      models: "Everything that understands, scores, decides, checks or advises, with its version.",
    },
  },
  zones: {
    axis: "Fraud score",
    noScore: "no score",
    rule: "Rule",
    decision: "Decision",
    block: "Card block",
    score: "Score",
    alsoHuman: "Also zone human, whatever the number",
    ticketAlways: "A case opens in every zone",
    amountGate: "Amount gate",
    approvalMode: "Approval mode",
    clock: "Regulatory clock",
    changes: "changes",
    never: "never changes",
    gateNote: "The amount only makes a money action's approval stricter; the legal deadline comes from the country table alone.",
    dataLabel: "[data] score bands as of today, from the EDA (policies.yaml zones)",
    fullRule: "Full rule",
    detailOpen: "Opens its rule.",
  },
  tools: {
    groups: { read: "Read", act: "Act", followUp: "Follow up", notify: "Notify" },
    groupNotes: {
      read: "Reads the customer's own data; changes nothing.",
      act: "The writes the graph's act node runs on a new dispute.",
      followUp: "Writes on a case that already exists.",
      notify: "Sends to a channel the customer confirmed.",
    },
    idempotent: "Idempotent: takes an idempotency key, so a retry never runs twice",
    verified: "Post-condition: verified by reading {tool}",
    kind: "Kind",
    purpose: "Purpose",
    verifiedWith: "Verified with",
    idempotency: "Idempotency key",
    yes: "yes",
    no: "no",
  },
  guardrails: {
    layer: "Layer",
    how: "How",
    citedBy: "Cited by policy ids",
    none: "none",
  },
  models: {
    tasks: { understands: "Understand", scores: "Score", decides: "Decide", checks: "Check", advises: "Advise" },
    kind: "Kind",
    version: "Version",
    role: "Role",
    source: "Source",
  },
} as const;

/** Fills `{name}` placeholders. */
export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
