// Every piece of /chat chrome text in one place (spec 07 AC-16 to AC-22), so the UI-language work can move it without
// hunting through components. Customer-facing words are ES/PT (the session language); the few operator controls of the
// demo stay in English. Nothing here carries a score, a zone or a policy id.
import type { Language } from "./types.ts";

type Bi<T = string> = Record<Language, T>;

export const CHAT_STRINGS = {
  assistant: { es: "Asistente de disputas", pt: "Assistente de disputas" } as Bi,
  online: { es: "En línea", pt: "Online" } as Bi,
  talkingWith: { es: (name: string) => `hablando con ${name}`, pt: (name: string) => `falando com ${name}` } as Bi<(name: string) => string>,
  newCase: { es: "Nuevo caso", pt: "Novo caso" } as Bi,
  newCaseHint: {
    es: "Empieza una conversación nueva. Tus casos abiertos se conservan.",
    pt: "Começa uma conversa nova. Seus casos abertos são mantidos.",
  } as Bi,
  demoNote: { es: "Demo con datos sintéticos", pt: "Demo com dados sintéticos" } as Bi,
  demoDate: { es: "fecha de la demo", pt: "data da demo" } as Bi,
  thinking: { es: "Pensando…", pt: "Pensando…" } as Bi,
  placeholder: {
    es: "Escribe o mantén presionado el micrófono para hablar",
    pt: "Escreva ou segure o microfone para falar",
  } as Bi,
  placeholderTyped: { es: "Escribe tu mensaje…", pt: "Escreva sua mensagem…" } as Bi,
  composerHint: {
    es: "Una persona del banco siempre está a un toque.",
    pt: "Uma pessoa do banco está sempre a um toque.",
  } as Bi,
  send: { es: "Enviar", pt: "Enviar" } as Bi,
  howDecided: { es: "Cómo lo decidí", pt: "Como decidi" } as Bi,
  steps: { es: (n: number) => (n === 1 ? "1 paso" : `${n} pasos`), pt: (n: number) => (n === 1 ? "1 etapa" : `${n} etapas`) } as Bi<(n: number) => string>,
  notCompleted: {
    es: (n: number) => (n === 1 ? "1 no se completó" : `${n} no se completaron`),
    pt: (n: number) => (n === 1 ? "1 não concluída" : `${n} não concluídas`),
  } as Bi<(n: number) => string>,
  working: { es: "Trabajando", pt: "Trabalhando" } as Bi,
  detail: { es: "detalle", pt: "detalhe" } as Bi,
  rule: { es: "ver regla", pt: "ver regra" } as Bi,
  technicalTrace: { es: "Ver traza técnica", pt: "Ver rastro técnico" } as Bi,
  hideTechnicalTrace: { es: "Ocultar traza técnica", pt: "Ocultar rastro técnico" } as Bi,
  confirmTitle: { es: "Antes de actuar necesito tu confirmación", pt: "Antes de agir preciso da sua confirmação" } as Bi,
  confirmYes: { es: "Sí, adelante", pt: "Sim, pode seguir" } as Bi,
  confirmNo: { es: "No, todavía no", pt: "Não, ainda não" } as Bi,
  copy: { es: "Copiar", pt: "Copiar" } as Bi,
  copied: { es: "Copiado", pt: "Copiado" } as Bi,
  copyReceipt: { es: "Copiar el comprobante", pt: "Copiar o comprovante" } as Bi,
  viewCase: { es: "Ver mi caso", pt: "Ver meu caso" } as Bi,
  source: { es: "Fuente", pt: "Fonte" } as Bi,
  sources: { es: "Fuentes", pt: "Fontes" } as Bi,
  verified: { es: "Verificado", pt: "Verificado" } as Bi,
  receipt: { es: "Comprobante", pt: "Comprovante" } as Bi,
  caseWord: { es: "caso", pt: "caso" } as Bi,
  then: { es: "luego, resolución a más tardar el", pt: "depois, resolução até" } as Bi,
  rowCharge: { es: "Cargo", pt: "Cobrança" } as Bi,
  rowDone: { es: "Hecho", pt: "Feito" } as Bi,
  rowNext: { es: "Sigue", pt: "Próximo" } as Bi,
  checkedOn: { es: "verificada el", pt: "verificada em" } as Bi,
  pick: { es: "Elegir", pt: "Escolher" } as Bi,
  citedFrom: { es: "Dato de la herramienta", pt: "Dado da ferramenta" } as Bi,
  openDetail: { es: "Ver detalle", pt: "Ver detalhe" } as Bi,
  close: { es: "Cerrar", pt: "Fechar" } as Bi,
  // The rule's detail panel (the mock's "Consultó la política del banco"): words only, never a score or a policy id.
  ruleTitle: { es: "Lo que dicen las reglas del banco", pt: "O que dizem as regras do banco" } as Bi,
  ruleLead: {
    es: "El asistente no decide: consulta las reglas del banco, y las reglas dicen qué puede hacer.",
    pt: "O assistente não decide: consulta as regras do banco, e as regras dizem o que ele pode fazer.",
  } as Bi,
  ruleResult: { es: "Resultado", pt: "Resultado" } as Bi,
  ruleAllowed: { es: "Acciones permitidas", pt: "Ações permitidas" } as Bi,
  ruleNote: {
    es: "En el chat no se muestran el puntaje del banco ni los códigos de las reglas. Una persona cierra cada caso.",
    pt: "No chat não aparecem a pontuação do banco nem os códigos das regras. Uma pessoa fecha cada caso.",
  } as Bi,
  stepStatus: { es: "Estado", pt: "Situação" } as Bi,
  stepResult: { es: "Resultado", pt: "Resultado" } as Bi,
  // The live graph beside the chat (spec 07 AC-31): the constitution in one line, and each node in plain words.
  graphToggle: { es: "Ver cómo trabaja", pt: "Ver como funciona" } as Bi,
  graphHide: { es: "Ocultar cómo trabaja", pt: "Ocultar como funciona" } as Bi,
  graphTitle: { es: "Cómo trabaja el asistente", pt: "Como o assistente trabalha" } as Bi,
  graphCaption: {
    es: "La IA entiende · las reglas deciden · las herramientas actúan · la verificación confirma · una persona cierra",
    pt: "A IA entende · as regras decidem · as ferramentas agem · a verificação confirma · uma pessoa fecha",
  } as Bi,
  graphNow: { es: "Ahora", pt: "Agora" } as Bi,
  graphIdle: { es: "Escribe un mensaje y verás cada paso aquí, en vivo.", pt: "Escreva uma mensagem e verá cada etapa aqui, ao vivo." } as Bi,
  graphDone: { es: "Turno terminado: el camino que siguió queda marcado.", pt: "Turno concluído: o caminho seguido fica marcado." } as Bi,
  graphNodes: {
    START: { es: "Inicio del turno", pt: "Início do turno" },
    identity: { es: "Confirmar tu sesión", pt: "Confirmar sua sessão" },
    greet: { es: "Revisar tu cuenta", pt: "Verificar sua conta" },
    understand: { es: "Entender tu mensaje", pt: "Entender sua mensagem" },
    route: { es: "Elegir el camino", pt: "Escolher o caminho" },
    refuse: { es: "Explicar por qué no se puede", pt: "Explicar por que não é possível" },
    connect: { es: "Pedir que te llame una persona", pt: "Pedir que uma pessoa ligue" },
    retrieve: { es: "Buscar el cargo", pt: "Buscar a cobrança" },
    decide: { es: "Aplicar las reglas del banco", pt: "Aplicar as regras do banco" },
    plan: { es: "Preparar los pasos", pt: "Preparar as etapas" },
    act: { es: "Abrir el caso y proteger la tarjeta", pt: "Abrir o caso e proteger o cartão" },
    verify: { es: "Confirmar en el sistema", pt: "Confirmar no sistema" },
    duplicate: { es: "Revisar si ya hay un caso", pt: "Verificar se já existe um caso" },
    clarify: { es: "Pedir un dato que falta", pt: "Pedir um dado que falta" },
    status: { es: "Leer el estado del caso", pt: "Ler a situação do caso" },
    respond: { es: "Escribir la respuesta", pt: "Escrever a resposta" },
    END: { es: "Turno terminado", pt: "Turno concluído" },
  } as Record<string, Bi>,
  signOut: { es: "Cerrar sesión", pt: "Sair" } as Bi,
  // The demo tools beside the chat (right-hand panels): they follow the session's conversation language.
  pickTitle: { es: "Elige un cargo para reclamar", pt: "Escolha uma cobrança para contestar" } as Bi,
  pickDescription: {
    es: "Tus cargos recientes con tarjeta. Un botón envía un mensaje que nombra el cargo; también puedes escribir.",
    pt: "Suas cobranças recentes no cartão. Um botão envia uma mensagem que identifica a cobrança; você também pode digitar.",
  } as Bi,
  loadingCharges: { es: "Cargando tus cargos…", pt: "Carregando suas cobranças…" } as Bi,
  cannotLoadCharges: { es: "No se pudieron cargar tus cargos", pt: "Não foi possível carregar suas cobranças" } as Bi,
  noCharges: { es: "No hay cargos recientes.", pt: "Nenhuma cobrança recente." } as Bi,
  testChargeTag: { es: "cargo de prueba", pt: "cobrança de teste" } as Bi,
  testTitle: { es: "Registrar un cargo de prueba", pt: "Registrar uma cobrança de teste" } as Bi,
  testDescription: {
    es: "Monto en la moneda de tu cliente y el nombre de un comercio. Aparece primero en la lista de arriba.",
    pt: "Valor na moeda do seu cliente e o nome de uma loja. Ela aparece primeiro na lista acima.",
  } as Bi,
  amountPlaceholder: { es: "Monto, p. ej. 1250.50", pt: "Valor, ex. 1250.50" } as Bi,
  amountLabel: { es: "Monto del cargo de prueba", pt: "Valor da cobrança de teste" } as Bi,
  merchantPlaceholder: { es: "Nombre del comercio", pt: "Nome da loja" } as Bi,
  merchantLabel: { es: "Comercio del cargo de prueba", pt: "Loja da cobrança de teste" } as Bi,
  register: { es: "Registrar", pt: "Registrar" } as Bi,
  registered: {
    es: (amount: string, currency: string, merchant: string) => `Cargo de prueba registrado: ${amount} ${currency} en ${merchant}.`,
    pt: (amount: string, currency: string, merchant: string) => `Cobrança de teste registrada: ${amount} ${currency} em ${merchant}.`,
  } as Bi<(amount: string, currency: string, merchant: string) => string>,
  rateLimited: { es: "Un cargo de prueba por minuto (tres por sesión).", pt: "Uma cobrança de teste por minuto (três por sessão)." } as Bi,
  notRegistered: { es: "No se registró", pt: "Não registrada" } as Bi,
  unexpectedError: { es: "error inesperado", pt: "erro inesperado" } as Bi,
  personasTitle: { es: "Prueba un tipo de cliente", pt: "Experimente um tipo de cliente" } as Bi,
  personasDescription: {
    es: "Sugiere un primer mensaje con la voz de ese personaje. Tú lo editas y lo envías.",
    pt: "Sugere uma primeira mensagem com a voz desse personagem. Você edita e envia.",
  } as Bi,
  noSuggestion: { es: "Sin sugerencia", pt: "Sem sugestão" } as Bi,
  personas: {
    aggressive: { es: "Agresivo", pt: "Agressivo" },
    passive: { es: "Pasivo", pt: "Passivo" },
    terse: { es: "Escueto", pt: "Lacônico" },
    verbose: { es: "Detallista", pt: "Prolixo" },
    confused: { es: "Confundido", pt: "Confuso" },
    code_switching: { es: "Mezcla ES/PT", pt: "Mistura ES/PT" },
  } as Record<string, Bi>,
  // Operator control of the demo (English UI).
  expire: "Expire session (demo)",
} as const;
