// Customer-facing ES/PT texts for the mock agent, copied from contracts/messages.yaml (spec 04 §4.2, §4.5; spec 01 §6.7).
// GENERATED by scripts/sync-messages.mjs (npm run sync:messages): do not edit by hand. `npm test` fails if it drifts.
// Placeholders use ONE syntax, {name}, filled only with facts returned by tools (ADR 0016).
// Nothing here may mention the score, policy ids, zones or the transcript.
import type { Language } from "../types.ts";

export interface Message {
  es: string;
  pt: string;
}

export const MESSAGES = {
  "greet": {
    "hello": {
      "es": "Hola, {first_name}. Soy el asistente de disputas de tu banco. Puedo:",
      "pt": "Olá, {first_name}. Sou o assistente de contestações do seu banco. Posso:"
    },
    "capability_1": {
      "es": "- Ayudarte a reportar un cargo que no reconoces o que fue incorrecto.",
      "pt": "- Ajudar você a informar uma cobrança que não reconhece ou que foi indevida."
    },
    "capability_2": {
      "es": "- Bloquear tu tarjeta cuando corresponde y confirmar que quedó bloqueada.",
      "pt": "- Bloquear seu cartão quando for o caso e confirmar que ele foi bloqueado."
    },
    "capability_3": {
      "es": "- Mostrarte el estado de tus tarjetas y de tus casos.",
      "pt": "- Mostrar a situação dos seus cartões e dos seus casos."
    },
    "human_review": {
      "es": "Una persona revisa los casos que lo necesitan.",
      "pt": "Uma pessoa revisa os casos que precisam disso."
    }
  },
  "plan": {
    "intro": {
      "es": "Esto es lo que voy a hacer:",
      "pt": "Vou fazer o seguinte:"
    },
    "step_open_case": {
      "es": "{step_n}. Abrir un caso con la información de este cargo ({merchant}, {amount} {currency}).",
      "pt": "{step_n}. Abrir um caso com as informações desta cobrança ({merchant}, {amount} {currency})."
    },
    "step_open_case_no_merchant": {
      "es": "{step_n}. Abrir un caso con la información de este cargo ({amount} {currency}).",
      "pt": "{step_n}. Abrir um caso com as informações desta cobrança ({amount} {currency})."
    },
    "step_block_card": {
      "es": "{step_n}. Bloquear tu tarjeta terminada en {last4}.",
      "pt": "{step_n}. Bloquear seu cartão com final {last4}."
    },
    "step_verify": {
      "es": "{step_n}. Verificar que el bloqueo y el caso quedaron registrados.",
      "pt": "{step_n}. Verificar se o bloqueio e o caso foram registrados."
    },
    "step_deadline": {
      "es": "{step_n}. Mostrarte la fecha límite legal y su fuente.",
      "pt": "{step_n}. Mostrar a você o prazo legal e a sua fonte."
    },
    "step_person": {
      "es": "{step_n}. Pasar el caso a una persona, que lo revisa y decide.",
      "pt": "{step_n}. Encaminhar o caso a uma pessoa, que vai analisar e decidir."
    },
    "confirm_ask": {
      "es": "¿Quieres que continúe con estos pasos?",
      "pt": "Quer que eu continue com estes passos?"
    }
  },
  "connect": {
    "requested": {
      "es": "Listo, registré tu solicitud. Una persona te llamará a más tardar el {expected_contact_by}.",
      "pt": "Pronto, registrei seu pedido. Uma pessoa vai ligar para você até {expected_contact_by}."
    },
    "requested_no_window": {
      "es": "Listo, registré tu solicitud para que una persona te llame.",
      "pt": "Pronto, registrei seu pedido para que uma pessoa ligue para você."
    }
  },
  "status": {
    "label": {
      "received": {
        "es": "Recibido",
        "pt": "Recebido"
      },
      "in_review": {
        "es": "En revisión",
        "pt": "Em análise"
      },
      "resolved": {
        "es": "Resuelto",
        "pt": "Resolvido"
      },
      "closed": {
        "es": "Cerrado",
        "pt": "Encerrado"
      }
    },
    "credit_deadline": {
      "es": "Plazo legal del banco para pronunciarse sobre los fondos en disputa: {credit_deadline}. Fuente: {deadline_source}.",
      "pt": "Prazo legal do banco para se pronunciar sobre os valores contestados: {credit_deadline}. Fonte: {deadline_source}."
    },
    "deadline_unknown": {
      "es": "Aún no hay un plazo legal verificado para tu caso; una persona lo confirmará.",
      "pt": "Ainda não há um prazo legal verificado para o seu caso; uma pessoa vai confirmá-lo."
    }
  },
  "suggest": {
    "report_unrecognized": {
      "es": "No reconozco un cargo",
      "pt": "Não reconheço uma cobrança"
    },
    "talk_to_person": {
      "es": "Hablar con una persona",
      "pt": "Falar com uma pessoa"
    },
    "confirm_yes": {
      "es": "Sí, continúa",
      "pt": "Sim, continue"
    },
    "confirm_no": {
      "es": "No es ese cargo",
      "pt": "Não é essa cobrança"
    },
    "add_info": {
      "es": "Agregar información",
      "pt": "Adicionar informações"
    },
    "request_call": {
      "es": "Que me llame una persona",
      "pt": "Quero que me liguem"
    },
    "view_case": {
      "es": "Ver mi caso",
      "pt": "Ver meu caso"
    }
  },
  "receipt": {
    "title": {
      "es": "Comprobante de tu caso {case_id}",
      "pt": "Comprovante do seu caso {case_id}"
    },
    "card_blocked": {
      "es": "Tarjeta terminada en {last4}: bloqueada y verificada (verificación {verification_id}, {verified_at}).",
      "pt": "Cartão com final {last4}: bloqueado e verificado (verificação {verification_id}, {verified_at})."
    },
    "what_ai_did_blocked": {
      "es": "Lo que hizo el asistente: abrió tu caso, bloqueó la tarjeta y verificó ambos pasos.",
      "pt": "O que o assistente fez: abriu seu caso, bloqueou o cartão e verificou as duas etapas."
    },
    "what_ai_did_case_only": {
      "es": "Lo que hizo el asistente: abrió tu caso y lo pasó a una persona.",
      "pt": "O que o assistente fez: abriu seu caso e o encaminhou a uma pessoa."
    },
    "what_a_person_does": {
      "es": "Lo que sigue: una persona revisa tu caso y toma la decisión. Te avisaremos cada vez que cambie su estado.",
      "pt": "O que vem a seguir: uma pessoa revisa seu caso e toma a decisão. Avisaremos você a cada mudança de situação."
    },
    "case_link": {
      "es": "Sigue tu caso aquí: {case_url}",
      "pt": "Acompanhe seu caso aqui: {case_url}"
    }
  }
} as const;

/** Fills {name} placeholders. A missing fact throws: a template that needs a fact the tool did not return is not rendered. */
export function fill(message: Message, lang: Language, facts: Record<string, string | number> = {}): string {
  return message[lang].replace(/\{([a-z_0-9]+)\}/g, (_m, name: string) => {
    const value = facts[name];
    if (value === undefined) throw new Error(`missing fact "${name}" for a customer message`);
    return String(value);
  });
}
